verbatim:
  cabal-version: 3.4

name: crowdfunding
version: 0.1.0.0

dependencies:
  - base >= 4.9 && < 5
  - cooked-validators
  - data-default
  - containers
  - QuickCheck
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - plutus-core
  - plutus-ledger
  - plutus-ledger-api
  - plutus-tx
  - plutus-tx-plugin
  - plutus-script-utils
  - plutus-use-cases

library:
  source-dirs: src
  ghc-options:
    -Wall
    -Werror

tests:
  spec:
    source-dirs: tests
    main: Spec.hs
    dependencies:
      - crowdfunding
    ghc-options:
      -threaded
      -Wall
      -Werror
