verbatim:
  cabal-version: 3.4

name: p-multisig-stateful
version: 0.1.0.0

dependencies:
  - base
  - bytestring
  - cooked-validators
  - aeson
  - data-default
  - flat
  - QuickCheck
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - tasty-expected-failure
  - plutus-tx
  - plutus-tx-plugin
  - plutus-ledger-api
  - plutus-ledger
  - plutus-script-utils
  - playground-common

library:
  source-dirs: src
  ghc-options:
    -Wall
    -Werror

tests:
  spec:
    source-dirs: tests
    main: Spec.hs
    dependencies:
      - p-multisig-stateful
    ghc-options:
      -threaded
      -Wall
      -Werror
