verbatim:
  cabal-version: 3.4

name: split-contract
version: 0.1.0.0

dependencies:
  - base >= 4.9 && < 5
  - cooked-validators
  - QuickCheck
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - tasty-expected-failure
  - aeson
  - bytestring
  - data-default
  - flat
  - hspec
  - plutus-core
  - plutus-ledger
  - plutus-ledger-api
  - plutus-tx
  - plutus-tx-plugin
  - plutus-contract
  - playground-common
  - plutus-script-utils
  - text
  - optics-core

library:
  source-dirs: src
  ghc-options:
    -Wall
    -fobject-code
    -fno-ignore-interface-pragmas
    -fno-omit-interface-pragmas

tests:
  spec:
    source-dirs: tests
    main: Spec.hs
    dependencies:
      - split-contract
    ghc-options:
      -threaded
