name: Build and test lotto contract

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    name: Build and run the test suites
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Build and generate validators (onchain code)
      run: |
        set -ex
        cd lotto/onchain
        pushd scripts
        cp -f lottoValidator.plutus lottoValidator.plutus.1
        cp -f sealMintingPolicy.plutus sealMintingPolicy.plutus.1
        popd
        nix run .#lotto-onchain --ply
        pushd scripts
        diff lottoValidator.plutus lottoValidator.plutus.1
        diff sealMintingPolicy.plutus sealMintingPolicy.plutus.1

    - name: Run the offchain tests
      run: |
        set -ex
        # The binary is directory-dependent, tests fail if the program is not
        # started from `lotto/offchain`
        cd lotto/offchain
        nix run .#lotto-offchain
